# Site settings
title: みっどメモ
header-img: img/home-bg.jpg
copyright_name: midchildan
description: "みっどちるだ人のブログ"
baseurl: ""
url: "http://blog.midchildan.org"
twitter_username: midchildan
github_username:  midchildan
# facebook_username:
# email_username:

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:
google_tag_id: GTM-P23WTL

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
timezone: Asia/Tokyo

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: post
            author: midchildan
            type: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jemoji]
